//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Втемя_роботы_сотрудника
    {
        public int Id { get; set; }
        public int id_Сотрудника { get; set; }
        public System.DateTime Начало_работы { get; set; }
        public System.DateTime Окончание_работы { get; set; }

        // public virtual Сотрудники Сотрудники { get; set; }
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }

        public Втемя_роботы_сотрудника()
        {
            Сотрудники = new List<Сотрудники>();
        }

    }
}
