//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Принятие_на_работу
    {
        public int Id { get; set; }
        public System.DateTime Дата_принятия_на_работу { get; set; }
        public int id_Сотрудника { get; set; }
    
       // public virtual Сотрудники Сотрудники { get; set; }
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }

        public Принятие_на_работу()
        {
            Сотрудники = new List<Сотрудники>();
        }
    }
}
